// <auto-generated />
using Logistics.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Logistics.DB.Migrations
{
    [DbContext(typeof(LogisticsContext))]
    partial class LogisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Logistics.DB.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("amountOfLetters")
                        .HasColumnType("int");

                    b.Property<string>("bagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("bagWeight")
                        .HasColumnType("real");

                    b.Property<float>("shippingPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("Logistics.DB.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parcelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("parcelPrice")
                        .HasColumnType("real");

                    b.Property<float>("parcelWeight")
                        .HasColumnType("real");

                    b.Property<string>("recipiantsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
